language: php

php:
  - 7
  - 7.1

before_script:
  - composer self-update
  - sudo apt-get install clamav -y
  - chmod 777 -R /var/log/clamav/
  - chmod 777 -R /var/lib/clamav/
  - composer install
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod 777 ./phpunit.phar

script:
  - ./phpunit.phar
