language: php

php:
  - 7
  - 7.1

before_script:
  - composer self-update
  - sudo apt-get update -y
  - sudo apt-get upgrade -y
  - sudo apt-get install clamav -y
  - composer install
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod 777 ./phpunit.phar

script:
  - ./phpunit.phar
