language: php

php:
  - 7
  - 7.1

before_script:
  - composer self-update
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install clamav
  - composer install
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod 777 ./phpunit.phar

script:
  - ./phpunit.phar
